### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by keanugithub** [balucio/dnsmasq-webgui#28]
i need help installing this on an armbian cli system thank you

**Comment by balucio** [comment]
The application is splitted in two components, a frontend (the web gui) and a backend.
First of all you have to compile the web application written using React Hooks. It requires `yarn` and `npm` installed.

```
git clone https://github.com/balucio/dnsmasq-webgui.git
cd dnsmasq-webgui/dns-webgui
# this will install the dependency
yarn install
# this will build the compiled web application, take a break because it requires time
yarn build
```
At end in `build` directory you should find the compiled application. You can test it using
```
DANGEROUSLY_DISABLE_HOST_CHECK=true yarn start
```
Then using your web browser connect to the page http://localhost:3000, you should see an empty page because no API backend is running. 

You can find the backend part into `dns-backend` directory of git repository.
In order to run this you need to setup a web server with the contents of the `build` directory (the React application) and the API backend (the `flask` appliction). To start you can watch the `apache-dnsapi-virtual-host.conf` file, which contains a sample Apache2 configuration file.
When your webserver is ready you have to install the two systemd descriptor files `dnsmonitor.path` that keep monitored the `/var/www/cgi-bin/dnsapi/hosts.db` for modifications and the `dnsmonitor.service`. The last one is triggered by `dnsmonitor.path` when a change to the `hosts.db` occurs, this service will run the `dnsapplyconfig.sh` script to update the dns configuration.

First of all the `dnsapplyconfig.sh` will execute the python script `dnsmasq-genhosts.py` into `/var/www/cgi-bin/dnsapi/` directory to get the new a new `dnsmasq`  hosts file, and  then will copy this file into your dns server and restart the `dnsmasq` service. The `dnsapplyconfig.sh` will connect to your DNS `dnsmasq` server using passwordless ssh (you have to set it), the DNS server is set at line 5 of this script:
```
dns_host="dns.example.it"
```
If you decide to install the webserver and `dnsmasq` on same server you may set this variable to `localhost`. In this case you can also decide to remove the `scp` command at all and use a simpe `cp` command to avoid to setup the passwordless `ssh`.

**Comment by keanugithub** [comment]
Hi thank you for your comprehensive reply. Just one last request. Can I have a screenshot of this project so I know when I finish if I did it correctly. Thanks again!

**Comment by balucio** [comment]
Hi, this is a screenshot of the Web UI. It is localized in italian but you could easily translate it replacing strings.

![image](https://user-images.githubusercontent.com/5398808/200119203-0e3d57cf-cb99-4efc-b725-a3d530a7ddbe.png)

**Comment by keanugithub** [comment]
Thank you, I appreciate this.
